# Generated by Django 4.2.2 on 2023-07-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('dessert', 'dessert'), ('beverage', 'beverage'), ('other', 'other')], default='other', max_length=10),
        ),
    ]
