# Generated by Django 4.2.2 on 2023-08-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_term_remove_recipe_thumbnail_tfidf_termdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfidf',
            name='score',
            field=models.FloatField(),
        ),
    ]
