# Generated by Django 5.0 on 2024-11-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_ingredientsection_ingredientlist_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='category',
            new_name='categories',
        ),
    ]
